name: CI Front-end

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cliente Angular
        run: npm install -g @angular/cli@16
      - name: Instalação de dependências
        working-directory: sgcmapp/
        run: npm install
      - name: e2e cypress
        working-directory: sgcmapp/
        run: ng run sgcmapp:cypress-run